language: python
sudo: false
dist: trusty
python:
    - "3.5"
    - "3.6"
install:
  - pip install tox

script:
- tox

matrix:
  include:
    - python: 3.5
      env:
      - TOXENV=py35
    - python: 3.6
      env:
      - TOXENV=py36